url: https://tr0py.github.io
baseurl:

# Site settings
title: RCSSA
email: rcssa@rice.edu
description: "Rice Chinese Students & Scholars Association"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - url: https://www.facebook.com/RiceRCSSA
    title: facebook

  - url: https://www.instagram.com/rice_rcssa/?hl=en
    title: instagram

  - title: wechat
    url: "/img/wechat.jpg"

# Postal address (add as many lines as necessary)
address:
  - line: RCSSA, Rice University
  - line: Houston, Texas 77005

# Build settings
markdown: kramdown
permalink: pretty

follow:
  - icon: weixin
    title: 微信公众号
    url: "/img/wechat.jpg"
  - icon: facebook-official
    title: Facebook
    url: https://www.facebook.com/RiceRCSSA
  - icon: instagram
    title: Instagram
    url: https://www.instagram.com/rice_rcssa/?hl=en
